export enum ScreenType {
  GREETING = "GREETING",
  PIN_FORM = "PIN_FORM",
  MENU = "MENU",
  MESSAGE = "MESSAGE",
  WITHDRAWAL_FORM = "WITHDRAWAL_FORM",
  WITHDRAWAL_CONFIRMATION = "WITHDRAWAL_CONFIRMATION",
  WITHDRAWAL_RESULT = "WITHDRAWAL_RESULT",
  OVERDRAFT_ALERT = "OVERDRAFT_ALERT",
}